### ISSUE TITLE
Update for new google forms code?

### ISSUE THREAD

**Issue by jeffmohr** [james2doyle/google-form-styling#1]
Thanks for this @james2doyle! Am I right that Google updated their forms code so this no longer works for styling? I'm seeing different classes on what Google provides.

**Comment by james2doyle** [comment]
Yeah it seems that way

**Comment by JacobLett** [comment]
I was able to create a solution using a cropped iframe. It doesn't capture a keyboard enter to submit the form but I think on mobile devices click/tap will work fine.

http://codepen.io/JacobLett/pen/dOLBOr

**Comment by james2doyle** [comment]
Closed with #3
